package cldrlocale_test

import (
	"bytes"
	"encoding/json"
	"go/parser"
	"go/token"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	cldrdisplaynames "github.com/agentable/go-intl/internal/cldr/displaynames"
	cldrlist "github.com/agentable/go-intl/internal/cldr/list"
	cldrlocale "github.com/agentable/go-intl/internal/cldr/locale"
	cldrnumber "github.com/agentable/go-intl/internal/cldr/number"
	cldrplural "github.com/agentable/go-intl/internal/cldr/plural"
	"github.com/agentable/go-intl/internal/localematcher"
	"github.com/agentable/go-intl/internal/testcontract"
)

// repoRoot is the module root relative to this package directory.
const repoRoot = "../../.."

func TestCLDRGeneratedDataContract(t *testing.T) {
	t.Parallel()

	version := cldrlocale.Version()
	if version.CLDR == "" || version.ICU == "" || version.TZData == "" {
		t.Fatalf("Version() = %#v, want all version fields populated", version)
	}
	manifest := cldrlocale.Manifest()
	if manifest.CLDR != version.CLDR || manifest.ICU != version.ICU || manifest.TZData != version.TZData {
		t.Fatalf("Manifest versions = %#v, Version = %#v", manifest, version)
	}
	if manifest.Generator != "tools/gen-cldr" {
		t.Fatalf("Manifest().Generator = %q, want tools/gen-cldr", manifest.Generator)
	}
	if len(manifest.LocaleProfile) == 0 {
		t.Fatal("Manifest().LocaleProfile is empty")
	}
	if len(manifest.InputHashes) == 0 {
		t.Fatal("Manifest().InputHashes is empty")
	}

	loc, ok := cldrnumber.ResolveLocale("en")
	if !ok {
		t.Fatal("ResolveLocale(en) failed")
	}
	if got := loc.CompactPattern("latn", "short", 3, "other"); got == "" {
		t.Fatal("CompactPattern(latn, 3, other) returned placeholder data")
	}
}

func TestManifestReturnsClonedSlices(t *testing.T) {
	t.Parallel()

	manifest := cldrlocale.Manifest()
	if len(manifest.LocaleProfile) == 0 || len(manifest.InputHashes) == 0 {
		t.Fatal("Manifest() returned empty slices")
	}
	manifest.LocaleProfile[0] = "mutated"
	manifest.InputHashes[0].SHA256 = "mutated"

	next := cldrlocale.Manifest()
	if next.LocaleProfile[0] == "mutated" {
		t.Fatal("Manifest().LocaleProfile shares mutable backing storage")
	}
	if next.InputHashes[0].SHA256 == "mutated" {
		t.Fatal("Manifest().InputHashes shares mutable backing storage")
	}
}

func TestManifestMatchesLocaleProfile(t *testing.T) {
	t.Parallel()

	root := filepath.Clean(repoRoot)
	want := readLocaleProfile(t, root)
	got := cldrlocale.Manifest().LocaleProfile
	requireSameStrings(t, "Manifest().LocaleProfile", got, want)
}

func TestDefaultDataProfilePolicy(t *testing.T) {
	t.Parallel()

	manifest := cldrlocale.Manifest()
	if manifest.CLDR != "48.1.0" || manifest.ICU != "78" || manifest.TZData != "2025b" {
		t.Fatalf("Manifest data pins = cldr=%s icu=%s tzdata=%s, want cldr=48.1.0 icu=78 tzdata=2025b", manifest.CLDR, manifest.ICU, manifest.TZData)
	}
	if got, want := len(manifest.LocaleProfile), 104; got != want {
		t.Fatalf("Manifest().LocaleProfile length = %d, want %d curated default locale tags", got, want)
	}
}

func TestCLDRBackedSupportedLocalesReflectProfile(t *testing.T) {
	t.Parallel()

	profile := cldrlocale.Manifest().LocaleProfile
	for _, tc := range []struct {
		name string
		got  []string
	}{
		{name: "number.SupportedLocales", got: cldrnumber.SupportedLocales()},
		{name: "list.SupportedLocales", got: cldrlist.SupportedLocales()},
		{name: "plural.SupportedLocales", got: cldrplural.SupportedLocales()},
		{name: "displaynames.SupportedLocales", got: cldrdisplaynames.SupportedLocales()},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			requireSupportedByProfile(t, tc.name, tc.got, profile)
		})
	}
}

func TestGeneratedFilesHaveHeaders(t *testing.T) {
	t.Parallel()

	root := filepath.Clean(repoRoot)
	files := generatedCLDRFiles(t, root)
	if len(files) == 0 {
		t.Fatal("no generated CLDR files discovered")
	}
	for _, path := range files {
		header := genCLDRHeader
		if strings.Contains(filepath.ToSlash(path), "/internal/cldr/plural/") {
			header = "// Code generated by tools/gen-plural-rules; DO NOT EDIT.\n"
		}
		t.Run(filepath.Base(path), func(t *testing.T) {
			t.Parallel()
			src, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("read file: %v", err)
			}
			if !bytes.HasPrefix(src, []byte(header)) {
				t.Fatalf("%s missing generated header", filepath.ToSlash(path))
			}
		})
	}
}

const genCLDRHeader = `// Code generated by tools/gen-cldr; see SPECS/50-cldr-data.md#cldr-pin-rationale; DO NOT EDIT.

// Source: CLDR v48.1.0 / ICU 78 / tzdata 2025b (input hashes in internal/cldr/locale/manifest.go)
// Generated: reproducible from tools/gen-cldr with pinned inputs; no timestamps or machine-local paths
// Schema: SPECS/50-cldr-data.md#cldr-data-package-convention
`

// generatedCLDRFiles walks internal/cldr and returns every generated Go file,
// identified by the generator header comment. The header gate checks the full
// set across all domain packages, not a fixed file list.
func generatedCLDRFiles(t *testing.T, root string) []string {
	t.Helper()

	cldrRoot := filepath.Join(root, "internal", "cldr")
	var files []string
	err := filepath.WalkDir(cldrRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		name := d.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			return nil
		}
		if isGeneratedCLDRSnapshotFile(t, path) {
			files = append(files, path)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk internal/cldr: %v", err)
	}
	slices.Sort(files)
	return files
}

// isGeneratedCLDRSnapshotFile reports whether the file carries a recognized
// generator header comment. Hand-written decode.go / accessors.go / doc.go and
// the codec package are excluded by lacking the header.
func isGeneratedCLDRSnapshotFile(t *testing.T, path string) bool {
	t.Helper()

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, parser.PackageClauseOnly|parser.ParseComments)
	if err != nil {
		t.Fatalf("parse comments %s: %v", path, err)
	}
	for _, group := range f.Comments {
		for _, c := range group.List {
			if strings.HasPrefix(c.Text, "// Code generated by tools/gen-cldr") ||
				strings.HasPrefix(c.Text, "// Code generated by tools/gen-plural-rules") {
				return true
			}
		}
	}
	return false
}

func readLocaleProfile(t *testing.T, root string) []string {
	t.Helper()

	raw, err := os.ReadFile(filepath.Join(root, "tools", "locale-profile.json"))
	if err != nil {
		t.Fatalf("read locale profile: %v", err)
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(raw, &fields); err != nil {
		t.Fatalf("parse locale profile fields: %v", err)
	}
	for key := range fields {
		if key != "locales" {
			t.Fatalf("tools/locale-profile.json contains unsupported key %q", key)
		}
	}
	var profile struct {
		Locales []string `json:"locales"`
	}
	if err := json.Unmarshal(raw, &profile); err != nil {
		t.Fatalf("parse locale profile: %v", err)
	}
	return sortedUniqueLocales(profile.Locales)
}

func sortedUniqueLocales(locales []string) []string {
	set := map[string]bool{}
	for _, locale := range locales {
		if locale != "" && locale != "und" {
			set[locale] = true
		}
	}
	return slices.Sorted(maps.Keys(set))
}

func requireSameStrings(t *testing.T, name string, got, want []string) {
	t.Helper()

	if slices.Equal(got, want) {
		return
	}
	t.Fatalf("%s = [%s], want [%s]", name, strings.Join(got, ", "), strings.Join(want, ", "))
}

func requireSupportedByProfile(t *testing.T, name string, supported, profile []string) {
	t.Helper()

	if len(supported) == 0 {
		t.Fatalf("%s is empty", name)
	}
	testcontract.AssertStringSliceSortedUnique(t, name, supported)

	profileSet := map[string]bool{}
	for _, locale := range profile {
		profileSet[locale] = true
	}
	for _, locale := range supported {
		if !profileSet[locale] {
			t.Fatalf("%s contains %q outside Manifest().LocaleProfile", name, locale)
		}
	}
	for _, locale := range profile {
		if localematcher.BestAvailableLocale(supported, locale) == "" {
			t.Fatalf("%s cannot support profile locale %q through ECMA-402 lookup", name, locale)
		}
	}
}
