// Code generated by tools/gen-cldr; see SPECS/50-cldr-data.md#cldr-pin-rationale; DO NOT EDIT.

// Source: CLDR v48.1.0 / ICU 78 / tzdata 2025b (input hashes in internal/cldr/locale/manifest.go)
// Generated: reproducible from tools/gen-cldr with pinned inputs; no timestamps or machine-local paths
// Schema: SPECS/50-cldr-data.md#cldr-data-package-convention
package cldrlocale

import "slices"

type regionTimeZonesRecord struct {
	region string
	zones  []string
}

var timeZonesByRegion = [...]regionTimeZonesRecord{
	{
		region: "BR",
		zones: []string{
			"America/Araguaina", "America/Bahia", "America/Belem", "America/Boa_Vista",
			"America/Campo_Grande", "America/Cuiaba", "America/Eirunepe", "America/Fortaleza",
			"America/Maceio", "America/Manaus", "America/Noronha", "America/Porto_Velho",
			"America/Recife", "America/Rio_Branco", "America/Santarem", "America/Sao_Paulo",
		},
	},
	{region: "CN", zones: []string{"Asia/Shanghai", "Asia/Urumqi"}},
	{region: "EG", zones: []string{"Africa/Cairo"}},
	{region: "GB", zones: []string{"Europe/London"}},
	{region: "IN", zones: []string{"Asia/Calcutta"}},
	{region: "SA", zones: []string{"Asia/Riyadh"}},
	{
		region: "US",
		zones: []string{
			"America/Adak", "America/Anchorage", "America/Boise", "America/Chicago",
			"America/Denver", "America/Detroit", "America/Indiana/Knox", "America/Indiana/Marengo",
			"America/Indiana/Petersburg", "America/Indiana/Tell_City", "America/Indiana/Vevay",
			"America/Indiana/Vincennes", "America/Indiana/Winamac", "America/Indianapolis",
			"America/Juneau", "America/Kentucky/Monticello", "America/Los_Angeles", "America/Louisville",
			"America/Menominee", "America/Metlakatla", "America/New_York", "America/Nome",
			"America/North_Dakota/Beulah", "America/North_Dakota/Center", "America/North_Dakota/New_Salem",
			"America/Phoenix", "America/Sitka", "America/Yakutat", "Pacific/Honolulu",
		},
	},
}

func CanonicalTimeZoneLink(name string) string {
	switch name {
	case "Africa/Timbuktu":
		return "Africa/Bamako"
	case "America/Montreal":
		return "America/Toronto"
	case "America/Nipigon":
		return "America/Toronto"
	case "America/Pangnirtung":
		return "America/Iqaluit"
	case "America/Rainy_River":
		return "America/Winnipeg"
	case "America/Santa_Isabel":
		return "America/Tijuana"
	case "America/Shiprock":
		return "America/Denver"
	case "America/Thunder_Bay":
		return "America/Toronto"
	case "America/Yellowknife":
		return "America/Edmonton"
	case "Antarctica/South_Pole":
		return "Pacific/Auckland"
	case "Asia/Calcutta":
		return "Asia/Kolkata"
	case "Asia/Choibalsan":
		return "Asia/Ulaanbaatar"
	case "Asia/Chongqing":
		return "Asia/Shanghai"
	case "Asia/Harbin":
		return "Asia/Shanghai"
	case "Asia/Kashgar":
		return "Asia/Urumqi"
	case "Atlantic/Jan_Mayen":
		return "Europe/Oslo"
	case "Australia/Currie":
		return "Australia/Hobart"
	case "CST6CDT":
		return "America/Chicago"
	case "EST":
		return "America/Panama"
	case "EST5EDT":
		return "America/New_York"
	case "Europe/Belfast":
		return "Europe/London"
	case "Europe/Uzhgorod":
		return "Europe/Kiev"
	case "Europe/Zaporozhye":
		return "Europe/Kiev"
	case "HST":
		return "Pacific/Honolulu"
	case "MST":
		return "America/Phoenix"
	case "MST7MDT":
		return "America/Denver"
	case "PST8PDT":
		return "America/Los_Angeles"
	case "Pacific/Johnston":
		return "Pacific/Honolulu"
	case "Pacific/Yap":
		return "Pacific/Truk"
	case "SystemV/AST4":
		return "America/Puerto_Rico"
	case "SystemV/AST4ADT":
		return "America/Halifax"
	case "SystemV/CST6":
		return "America/Regina"
	case "SystemV/CST6CDT":
		return "America/Chicago"
	case "SystemV/EST5":
		return "America/Indianapolis"
	case "SystemV/EST5EDT":
		return "America/New_York"
	case "SystemV/HST10":
		return "Pacific/Honolulu"
	case "SystemV/MST7":
		return "America/Phoenix"
	case "SystemV/MST7MDT":
		return "America/Denver"
	case "SystemV/PST8":
		return "Pacific/Pitcairn"
	case "SystemV/PST8PDT":
		return "America/Los_Angeles"
	case "SystemV/YST9":
		return "Pacific/Gambier"
	case "SystemV/YST9YDT":
		return "America/Anchorage"
	case "US/Eastern":
		return "America/New_York"
	case "US/Pacific":
		return "America/Los_Angeles"
	}
	return name
}

func TimeZonesForRegion(region string) []string {
	for _, record := range timeZonesByRegion[:] {
		if record.region == region {
			return slices.Clone(record.zones)
		}
	}
	return nil
}
