// Code generated by tools/gen-cldr; see SPECS/50-cldr-data.md#cldr-pin-rationale; DO NOT EDIT.

// Source: CLDR v48.1.0 / ICU 78 / tzdata 2025b (input hashes in internal/cldr/locale/manifest.go)
// Generated: reproducible from tools/gen-cldr with pinned inputs; no timestamps or machine-local paths
// Schema: SPECS/50-cldr-data.md#cldr-data-package-convention
package cldrlocale

import "slices"

type regionTimeZonesRecord struct {
	region string
	zones  []string
}

var timeZonesByRegion = [...]regionTimeZonesRecord{
	{
		region: "BR",
		zones: []string{
			"America/Araguaina", "America/Bahia", "America/Belem", "America/Boa_Vista",
			"America/Campo_Grande", "America/Cuiaba", "America/Eirunepe", "America/Fortaleza",
			"America/Maceio", "America/Manaus", "America/Noronha", "America/Porto_Velho",
			"America/Recife", "America/Rio_Branco", "America/Santarem", "America/Sao_Paulo",
		},
	},
	{region: "CN", zones: []string{"Asia/Shanghai", "Asia/Urumqi"}},
	{region: "EG", zones: []string{"Africa/Cairo"}},
	{region: "GB", zones: []string{"Europe/London"}},
	{region: "IN", zones: []string{"Asia/Calcutta"}},
	{region: "SA", zones: []string{"Asia/Riyadh"}},
	{
		region: "US",
		zones: []string{
			"America/Adak", "America/Anchorage", "America/Boise", "America/Chicago",
			"America/Denver", "America/Detroit", "America/Indiana/Knox", "America/Indiana/Marengo",
			"America/Indiana/Petersburg", "America/Indiana/Tell_City", "America/Indiana/Vevay",
			"America/Indiana/Vincennes", "America/Indiana/Winamac", "America/Indianapolis",
			"America/Juneau", "America/Kentucky/Monticello", "America/Los_Angeles", "America/Louisville",
			"America/Menominee", "America/Metlakatla", "America/New_York", "America/Nome",
			"America/North_Dakota/Beulah", "America/North_Dakota/Center", "America/North_Dakota/New_Salem",
			"America/Phoenix", "America/Sitka", "America/Yakutat", "Pacific/Honolulu",
		},
	},
}

func CanonicalTimeZoneLink(name string) string {
	switch name {
	case "US/Eastern":
		return "America/New_York"
	case "US/Pacific":
		return "America/Los_Angeles"
	case "Asia/Calcutta":
		return "Asia/Kolkata"
	}
	return name
}

func TimeZonesForRegion(region string) []string {
	for _, record := range timeZonesByRegion[:] {
		if record.region == region {
			return slices.Clone(record.zones)
		}
	}
	return nil
}
