// Code generated by tools/gen-cldr; see SPECS/50-cldr-data.md#cldr-pin-rationale; DO NOT EDIT.

// Source: CLDR v48.1.0 / ICU 78 / tzdata 2025b (input hashes in internal/cldr/manifest.go)
// Generated: reproducible from tools/gen-cldr with pinned inputs; no timestamps or machine-local paths
// Schema: SPECS/50-cldr-data.md#cldr-data-package-convention
package relativetime

import "github.com/agentable/go-intl/internal/cldr"

type Locale = cldr.Locale
type RelativeTimeField = cldr.RelativeTimeField
type RelativeTimeFields = cldr.RelativeTimeFields

func SupportedLocales() []string {
	return cldr.RelativeTimeSupportedLocales()
}

func ResolveLocale(tag string) (Locale, bool) {
	return cldr.ResolveLocale(tag)
}

func FieldsFor(loc Locale) RelativeTimeFields {
	return loc.RelativeTimeFields()
}
