package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParsePluralRulesJSON(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writePluralRuleFixtures(t, dir)

	cardinal, ordinal, err := parsePluralRules(filepath.Join(dir, "plurals.json"), testPluralLocales())
	if err != nil {
		t.Fatal(err)
	}
	if got := cardinal["en"][0]; got.Category != "one" || got.Expr != "i = 1 and v = 0" {
		t.Fatalf("cardinal en first rule = %+v", got)
	}
	if _, ok := cardinal["en-US"]; !ok {
		t.Fatal("cardinal en-US alias missing")
	}
	if _, ok := cardinal["zh-Hans-CN"]; !ok {
		t.Fatal("cardinal zh-Hans-CN parent rule missing")
	}
	if got := ordinal["en"][0]; got.Category != "one" || got.Expr != "n % 10 = 1 and n % 100 != 11" {
		t.Fatalf("ordinal en first rule = %+v", got)
	}
}

func TestParsePluralRangesJSON(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writePluralRuleFixtures(t, dir)

	ranges, err := parsePluralRanges(filepath.Join(dir, "pluralRanges.json"), testPluralLocales())
	if err != nil {
		t.Fatal(err)
	}
	if got := ranges["en"][RangeKey{Start: "one", End: "other"}]; got != "other" {
		t.Fatalf("range en one-other = %q, want other", got)
	}
	if _, ok := ranges["en-US"]; !ok {
		t.Fatal("range en-US alias missing")
	}
}

func TestRunGeneratesPluralRuleFiles(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writePluralRuleFixtures(t, dir)
	out := filepath.Join(dir, "out")

	err := run([]string{
		"-plurals", filepath.Join(dir, "plurals.json"),
		"-ranges", filepath.Join(dir, "pluralRanges.json"),
		"-out", out,
		"-profile", writeLocaleProfileFixture(t, dir),
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"cardinal_rules.go", "ordinal_rules.go", "range_rules.go", "categories.go", "supported.go"} {
		raw, err := os.ReadFile(filepath.Join(out, name))
		if err != nil {
			t.Fatalf("read generated %s: %v", name, err)
		}
		if !strings.Contains(string(raw), "Code generated by tools/gen-plural-rules") {
			t.Fatalf("%s missing generated header:\n%s", name, raw)
		}
	}
	cardinal, err := os.ReadFile(filepath.Join(out, "cardinal_rules.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !containsAll(string(cardinal), "func CardinalRule", "cardinalEnUS", "cardinalZhHansCN", "cardinalPl", "o.N.Mod(100).Between(3, 10)") {
		t.Fatalf("cardinal_rules.go missing compiled rules:\n%s", cardinal)
	}
	supported, err := os.ReadFile(filepath.Join(out, "supported.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !containsAll(string(supported), "func SupportedLocales() []string", `"en-US"`, `"zh-Hans-CN"`) {
		t.Fatalf("supported.go missing plural locale list:\n%s", supported)
	}
}

func TestCompileCondition(t *testing.T) {
	t.Parallel()

	tests := []struct {
		in   string
		want string
	}{
		{in: "i = 1 and v = 0", want: "o.I.Equal(1) && o.V == 0"},
		{in: "i % 10 = 2..4 and i % 100 != 12..14", want: "o.I.Mod(10).Between(2, 4) && o.I.Mod(100).OutsideRange(12, 14)"},
		{in: "n % 100 = 3..10", want: "o.N.Mod(100).Between(3, 10)"},
	}
	for _, tc := range tests {
		if got := compileCondition(tc.in); got != tc.want {
			t.Fatalf("compileCondition(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func writePluralRuleFixtures(t *testing.T, dir string) {
	t.Helper()
	plurals := `{"supplemental":{"plurals-type-cardinal":{
		"en":{"pluralRule-count-one":"i = 1 and v = 0 @integer 1","pluralRule-count-other":" @integer 0, 2"},
		"pl":{"pluralRule-count-one":"i = 1 and v = 0 @integer 1","pluralRule-count-few":"v = 0 and i % 10 = 2..4 and i % 100 != 12..14 @integer 2","pluralRule-count-other":" @integer 0"},
		"ar":{"pluralRule-count-few":"n % 100 = 3..10 @integer 3","pluralRule-count-other":" @integer 0"},
		"fr":{"pluralRule-count-one":"i = 0,1 @integer 0, 1","pluralRule-count-other":" @integer 2"},
		"zh":{"pluralRule-count-other":" @integer 0"}
	}}}`
	ordinals := `{"supplemental":{"plurals-type-ordinal":{
		"en":{"pluralRule-count-one":"n % 10 = 1 and n % 100 != 11 @integer 1","pluralRule-count-other":" @integer 0"},
		"pl":{"pluralRule-count-other":" @integer 0"},
		"ar":{"pluralRule-count-other":" @integer 0"},
		"fr":{"pluralRule-count-one":"n = 1 @integer 1","pluralRule-count-other":" @integer 0"},
		"zh":{"pluralRule-count-other":" @integer 0"}
	}}}`
	ranges := `{"supplemental":{"plurals":{
		"en":{"pluralRange-start-one-end-other":"other","pluralRange-start-other-end-other":"other"},
		"fr":{"pluralRange-start-one-end-one":"one","pluralRange-start-one-end-other":"other","pluralRange-start-other-end-other":"other"}
	}}}`
	for name, data := range map[string]string{"plurals.json": plurals, "ordinals.json": ordinals, "pluralRanges.json": ranges} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(data), 0o666); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}
}

func testPluralLocales() []string {
	return []string{"ar", "en", "en-US", "fr", "pl", "zh", "zh-Hans", "zh-Hans-CN"}
}

func writeLocaleProfileFixture(t *testing.T, dir string) string {
	t.Helper()
	path := filepath.Join(dir, "locale-profile.json")
	profile := `{"locales":["ar","en","en-US","fr","pl","zh","zh-Hans","zh-Hans-CN"]}`
	if err := os.WriteFile(path, []byte(profile), 0o666); err != nil {
		t.Fatalf("write locale profile: %v", err)
	}
	return path
}

func containsAll(s string, needles ...string) bool {
	for _, needle := range needles {
		if !strings.Contains(s, needle) {
			return false
		}
	}
	return true
}
