package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const generatedTestHeader = "// Code generated by tools/gen-cldr; DO NOT EDIT.\n"

func TestCompareGeneratedDataRejectsMissingFreshPath(t *testing.T) {
	t.Parallel()

	committed := t.TempDir()
	generated := t.TempDir()
	writeGeneratedTestFile(t, committed, "cldr/number/data.go", generatedTestHeader+"package number\n")

	err := compareGeneratedData(committed, generated)
	if err == nil || !strings.Contains(err.Error(), "cldr/number/data.go") {
		t.Fatalf("compareGeneratedData() error = %v, want missing path", err)
	}
}

func TestCompareGeneratedDataRejectsUnexpectedFreshPath(t *testing.T) {
	t.Parallel()

	committed := t.TempDir()
	generated := t.TempDir()
	writeGeneratedTestFile(t, generated, "tz/registry_data.go", generatedTestHeader+"package tz\n")

	err := compareGeneratedData(committed, generated)
	if err == nil || !strings.Contains(err.Error(), "tz/registry_data.go") {
		t.Fatalf("compareGeneratedData() error = %v, want unexpected path", err)
	}
}

func TestCompareGeneratedDataRejectsDifferentBytes(t *testing.T) {
	t.Parallel()

	committed := t.TempDir()
	generated := t.TempDir()
	const path = "cldr/plural/cardinal_rules.go"
	writeGeneratedTestFile(t, committed, path, generatedTestHeader+"package plural\nconst version = 1\n")
	writeGeneratedTestFile(t, generated, path, generatedTestHeader+"package plural\nconst version = 2\n")

	err := compareGeneratedData(committed, generated)
	if err == nil || !strings.Contains(err.Error(), path) {
		t.Fatalf("compareGeneratedData() error = %v, want byte mismatch", err)
	}
}

func TestCompareGeneratedDataRejectsMovedPath(t *testing.T) {
	t.Parallel()

	committed := t.TempDir()
	generated := t.TempDir()
	writeGeneratedTestFile(t, committed, "cldr/old/data.go", generatedTestHeader+"package old\n")
	writeGeneratedTestFile(t, generated, "cldr/new/data.go", generatedTestHeader+"package old\n")

	if err := compareGeneratedData(committed, generated); err == nil {
		t.Fatal("compareGeneratedData() error = nil, want moved path failure")
	}
}

func TestCompareGeneratedDataAcceptsIdenticalOwnedPathsAndIgnoresHandwrittenFiles(t *testing.T) {
	t.Parallel()

	committed := t.TempDir()
	generated := t.TempDir()
	files := map[string]string{
		"cldr/number/data.go":           generatedTestHeader + "package number\n",
		"cldr/plural/supported.go":      "// Code generated by tools/gen-plural-rules; DO NOT EDIT.\npackage plural\n",
		"cldr/number/accessors.go":      "package number\n",
		"localematcher/profile_data.go": generatedTestHeader + "package localematcher\n",
	}
	for path, contents := range files {
		writeGeneratedTestFile(t, committed, path, contents)
		writeGeneratedTestFile(t, generated, path, contents)
	}
	writeGeneratedTestFile(t, committed, "cldr/number/decode.go", "package number\n")
	writeGeneratedTestFile(t, generated, "cldr/number/decode.go", "package number\n// fresh handwritten difference\n")

	if err := compareGeneratedData(committed, generated); err != nil {
		t.Fatalf("compareGeneratedData() error = %v, want nil", err)
	}
}

func TestLoadGeneratedFilesRejectsSymlinkEscape(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	externalRoot := t.TempDir()
	externalPath := filepath.Join(externalRoot, "data.go")
	if err := os.WriteFile(externalPath, []byte(generatedTestHeader+"package external\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(externalPath, filepath.Join(root, "data.go")); err != nil {
		t.Skipf("create symlink: %v", err)
	}

	if _, err := loadGeneratedFiles(root); err == nil {
		t.Fatal("loadGeneratedFiles() error = nil, want symlink escape rejection")
	}
}

func writeGeneratedTestFile(t *testing.T, root, rel, contents string) {
	t.Helper()

	path := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatal(err)
	}
}
