package main

import (
	"bytes"
	"fmt"
	"io/fs"
	"maps"
	"os"
	"slices"
)

const (
	genCLDRHeaderPrefix   = "// Code generated by tools/gen-cldr;"
	genPluralHeaderPrefix = "// Code generated by tools/gen-plural-rules;"
)

func compareGeneratedData(committedRoot, generatedRoot string) error {
	committed, err := loadGeneratedFiles(committedRoot)
	if err != nil {
		return err
	}
	generated, err := loadGeneratedFiles(generatedRoot)
	if err != nil {
		return err
	}
	for _, path := range slices.Sorted(maps.Keys(committed)) {
		fresh, ok := generated[path]
		if !ok {
			return fmt.Errorf("generated path %s is missing from fresh output", path)
		}
		if !bytes.Equal(committed[path], fresh) {
			return fmt.Errorf("generated path %s differs from fresh output", path)
		}
	}
	for _, path := range slices.Sorted(maps.Keys(generated)) {
		if _, ok := committed[path]; !ok {
			return fmt.Errorf("fresh generated path %s is missing from the committed tree", path)
		}
	}
	return nil
}

func loadGeneratedFiles(root string) (map[string][]byte, error) {
	dir, err := os.OpenRoot(root)
	if err != nil {
		return nil, fmt.Errorf("open generated files root %s: %w", root, err)
	}

	files := map[string][]byte{}
	walkErr := fs.WalkDir(dir.FS(), ".", func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		data, err := dir.ReadFile(path)
		if err != nil {
			return err
		}
		if !isGeneratedFile(data) {
			return nil
		}
		files[path] = data
		return nil
	})
	closeErr := dir.Close()
	if walkErr != nil {
		return nil, fmt.Errorf("walk generated files in %s: %w", root, walkErr)
	}
	if closeErr != nil {
		return nil, fmt.Errorf("close generated files root %s: %w", root, closeErr)
	}
	return files, nil
}

func isGeneratedFile(data []byte) bool {
	return bytes.HasPrefix(data, []byte(genCLDRHeaderPrefix)) ||
		bytes.HasPrefix(data, []byte(genPluralHeaderPrefix))
}
