// Code generated by tools/gen-plural-rules; DO NOT EDIT.
// CLDR version: 48.1.0

package plural

import ecma402pr "github.com/agentable/go-intl/internal/ecma402/pluralrules"

func CardinalRule(loc string) (func(ecma402pr.OperandsRecord) ecma402pr.Category, bool) {
	switch loc {
	case "ar":
		return cardinalAr, true
	case "en":
		return cardinalEn, true
	case "en-US":
		return cardinalEnUS, true
	case "fr":
		return cardinalFr, true
	case "hi":
		return cardinalHi, true
	case "pl":
		return cardinalPl, true
	case "zh":
		return cardinalZh, true
	case "zh-Hans":
		return cardinalZhHans, true
	case "zh-Hans-CN":
		return cardinalZhHansCN, true
	}
	return nil, false
}

func cardinalAr(o ecma402pr.OperandsRecord) ecma402pr.Category {
	if o.N.EqualInt(0) {
		return ecma402pr.Zero
	}
	if o.N.EqualInt(1) {
		return ecma402pr.One
	}
	if o.N.EqualInt(2) {
		return ecma402pr.Two
	}
	if o.N.ModInt(100).BetweenInt(3, 10) {
		return ecma402pr.Few
	}
	if o.N.ModInt(100).BetweenInt(11, 99) {
		return ecma402pr.Many
	}
	return ecma402pr.Other
}

func cardinalEn(o ecma402pr.OperandsRecord) ecma402pr.Category {
	if o.I.EqualInt(1) && o.V == 0 {
		return ecma402pr.One
	}
	return ecma402pr.Other
}

func cardinalEnUS(o ecma402pr.OperandsRecord) ecma402pr.Category {
	if o.I.EqualInt(1) && o.V == 0 {
		return ecma402pr.One
	}
	return ecma402pr.Other
}

func cardinalFr(o ecma402pr.OperandsRecord) ecma402pr.Category {
	if o.I.EqualInt(0) || o.I.EqualInt(1) {
		return ecma402pr.One
	}
	if (o.E == 0 && o.I.NotEqualInt(0) && o.I.ModInt(1000000).EqualInt(0) && o.V == 0) || (o.E < 0 || o.E > 5) {
		return ecma402pr.Many
	}
	return ecma402pr.Other
}

func cardinalHi(o ecma402pr.OperandsRecord) ecma402pr.Category {
	if (o.I.EqualInt(0)) || (o.N.EqualInt(1)) {
		return ecma402pr.One
	}
	return ecma402pr.Other
}

func cardinalPl(o ecma402pr.OperandsRecord) ecma402pr.Category {
	if o.I.EqualInt(1) && o.V == 0 {
		return ecma402pr.One
	}
	if o.V == 0 && o.I.ModInt(10).BetweenInt(2, 4) && o.I.ModInt(100).OutsideIntRange(12, 14) {
		return ecma402pr.Few
	}
	if (o.V == 0 && o.I.NotEqualInt(1) && o.I.ModInt(10).BetweenInt(0, 1)) || (o.V == 0 && o.I.ModInt(10).BetweenInt(5, 9)) || (o.V == 0 && o.I.ModInt(100).BetweenInt(12, 14)) {
		return ecma402pr.Many
	}
	return ecma402pr.Other
}

func cardinalZh(o ecma402pr.OperandsRecord) ecma402pr.Category {
	return ecma402pr.Other
}

func cardinalZhHans(o ecma402pr.OperandsRecord) ecma402pr.Category {
	return ecma402pr.Other
}

func cardinalZhHansCN(o ecma402pr.OperandsRecord) ecma402pr.Category {
	return ecma402pr.Other
}

func cardinalOther(ecma402pr.OperandsRecord) ecma402pr.Category {
	return ecma402pr.Other
}
