// Code generated by tools/gen-plural-rules; DO NOT EDIT.
// CLDR version: 48.1.0

package plural

import ecma402pr "github.com/agentable/go-intl/internal/ecma402/pluralrules"

func Categories(loc, typ string) []ecma402pr.Category {
	if typ == "ordinal" {
		switch loc {
		case "ar":
			return []ecma402pr.Category{ecma402pr.Other}
		case "en":
			return []ecma402pr.Category{ecma402pr.One, ecma402pr.Two, ecma402pr.Few, ecma402pr.Other}
		case "en-US":
			return []ecma402pr.Category{ecma402pr.One, ecma402pr.Two, ecma402pr.Few, ecma402pr.Other}
		case "fr":
			return []ecma402pr.Category{ecma402pr.One, ecma402pr.Other}
		case "hi":
			return []ecma402pr.Category{ecma402pr.One, ecma402pr.Two, ecma402pr.Few, ecma402pr.Many, ecma402pr.Other}
		case "pl":
			return []ecma402pr.Category{ecma402pr.Other}
		case "zh":
			return []ecma402pr.Category{ecma402pr.Other}
		case "zh-Hans":
			return []ecma402pr.Category{ecma402pr.Other}
		case "zh-Hans-CN":
			return []ecma402pr.Category{ecma402pr.Other}
		}
		return []ecma402pr.Category{ecma402pr.Other}
	}
	switch loc {
	case "ar":
		return []ecma402pr.Category{ecma402pr.Zero, ecma402pr.One, ecma402pr.Two, ecma402pr.Few, ecma402pr.Many, ecma402pr.Other}
	case "en":
		return []ecma402pr.Category{ecma402pr.One, ecma402pr.Other}
	case "en-US":
		return []ecma402pr.Category{ecma402pr.One, ecma402pr.Other}
	case "fr":
		return []ecma402pr.Category{ecma402pr.One, ecma402pr.Many, ecma402pr.Other}
	case "hi":
		return []ecma402pr.Category{ecma402pr.One, ecma402pr.Other}
	case "pl":
		return []ecma402pr.Category{ecma402pr.One, ecma402pr.Few, ecma402pr.Many, ecma402pr.Other}
	case "zh":
		return []ecma402pr.Category{ecma402pr.Other}
	case "zh-Hans":
		return []ecma402pr.Category{ecma402pr.Other}
	case "zh-Hans-CN":
		return []ecma402pr.Category{ecma402pr.Other}
	}
	return []ecma402pr.Category{ecma402pr.Other}
}
