// Code generated by tools/gen-plural-rules; DO NOT EDIT.
// CLDR version: 48.1.0

package plural

import ecma402pr "github.com/agentable/go-intl/internal/ecma402/pluralrules"

func OrdinalRule(loc string) (func(ecma402pr.OperandsRecord) ecma402pr.Category, bool) {
	switch loc {
	case "ar":
		return ordinalAr, true
	case "en":
		return ordinalEn, true
	case "en-US":
		return ordinalEnUS, true
	case "fr":
		return ordinalFr, true
	case "hi":
		return ordinalHi, true
	case "pl":
		return ordinalPl, true
	case "zh":
		return ordinalZh, true
	case "zh-Hans":
		return ordinalZhHans, true
	case "zh-Hans-CN":
		return ordinalZhHansCN, true
	}
	return cardinalOther, true
}

func ordinalAr(o ecma402pr.OperandsRecord) ecma402pr.Category {
	return ecma402pr.Other
}

func ordinalEn(o ecma402pr.OperandsRecord) ecma402pr.Category {
	if o.N.ModInt(10).EqualInt(1) && o.N.ModInt(100).NotEqualInt(11) {
		return ecma402pr.One
	}
	if o.N.ModInt(10).EqualInt(2) && o.N.ModInt(100).NotEqualInt(12) {
		return ecma402pr.Two
	}
	if o.N.ModInt(10).EqualInt(3) && o.N.ModInt(100).NotEqualInt(13) {
		return ecma402pr.Few
	}
	return ecma402pr.Other
}

func ordinalEnUS(o ecma402pr.OperandsRecord) ecma402pr.Category {
	if o.N.ModInt(10).EqualInt(1) && o.N.ModInt(100).NotEqualInt(11) {
		return ecma402pr.One
	}
	if o.N.ModInt(10).EqualInt(2) && o.N.ModInt(100).NotEqualInt(12) {
		return ecma402pr.Two
	}
	if o.N.ModInt(10).EqualInt(3) && o.N.ModInt(100).NotEqualInt(13) {
		return ecma402pr.Few
	}
	return ecma402pr.Other
}

func ordinalFr(o ecma402pr.OperandsRecord) ecma402pr.Category {
	if o.N.EqualInt(1) {
		return ecma402pr.One
	}
	return ecma402pr.Other
}

func ordinalHi(o ecma402pr.OperandsRecord) ecma402pr.Category {
	if o.N.EqualInt(1) {
		return ecma402pr.One
	}
	if o.N.EqualInt(2) || o.N.EqualInt(3) {
		return ecma402pr.Two
	}
	if o.N.EqualInt(4) {
		return ecma402pr.Few
	}
	if o.N.EqualInt(6) {
		return ecma402pr.Many
	}
	return ecma402pr.Other
}

func ordinalPl(o ecma402pr.OperandsRecord) ecma402pr.Category {
	return ecma402pr.Other
}

func ordinalZh(o ecma402pr.OperandsRecord) ecma402pr.Category {
	return ecma402pr.Other
}

func ordinalZhHans(o ecma402pr.OperandsRecord) ecma402pr.Category {
	return ecma402pr.Other
}

func ordinalZhHansCN(o ecma402pr.OperandsRecord) ecma402pr.Category {
	return ecma402pr.Other
}
