// Code generated by tools/gen-plural-rules; DO NOT EDIT.
// CLDR version: 48.1.0

package plural

import ecma402pr "github.com/agentable/go-intl/internal/ecma402/pluralrules"

type rangeKey struct {
	start ecma402pr.Category
	end   ecma402pr.Category
}

func Range(loc, typ string, start, end ecma402pr.Category) (ecma402pr.Category, bool) {
	if typ == "ordinal" {
		return 0, false
	}
	ranges, ok := cardinalRanges[loc]
	if !ok {
		return 0, false
	}
	cat, ok := ranges[rangeKey{start: start, end: end}]
	return cat, ok
}

var cardinalRanges = map[string]map[rangeKey]ecma402pr.Category{
	"ar": {
		{start: ecma402pr.Few, end: ecma402pr.Few}:     ecma402pr.Few,
		{start: ecma402pr.Few, end: ecma402pr.Many}:    ecma402pr.Many,
		{start: ecma402pr.Few, end: ecma402pr.Other}:   ecma402pr.Other,
		{start: ecma402pr.Many, end: ecma402pr.Few}:    ecma402pr.Few,
		{start: ecma402pr.Many, end: ecma402pr.Many}:   ecma402pr.Many,
		{start: ecma402pr.Many, end: ecma402pr.Other}:  ecma402pr.Other,
		{start: ecma402pr.One, end: ecma402pr.Few}:     ecma402pr.Few,
		{start: ecma402pr.One, end: ecma402pr.Many}:    ecma402pr.Many,
		{start: ecma402pr.One, end: ecma402pr.Other}:   ecma402pr.Other,
		{start: ecma402pr.One, end: ecma402pr.Two}:     ecma402pr.Other,
		{start: ecma402pr.Other, end: ecma402pr.Few}:   ecma402pr.Few,
		{start: ecma402pr.Other, end: ecma402pr.Many}:  ecma402pr.Many,
		{start: ecma402pr.Other, end: ecma402pr.One}:   ecma402pr.Other,
		{start: ecma402pr.Other, end: ecma402pr.Other}: ecma402pr.Other,
		{start: ecma402pr.Other, end: ecma402pr.Two}:   ecma402pr.Other,
		{start: ecma402pr.Two, end: ecma402pr.Few}:     ecma402pr.Few,
		{start: ecma402pr.Two, end: ecma402pr.Many}:    ecma402pr.Many,
		{start: ecma402pr.Two, end: ecma402pr.Other}:   ecma402pr.Other,
		{start: ecma402pr.Zero, end: ecma402pr.Few}:    ecma402pr.Few,
		{start: ecma402pr.Zero, end: ecma402pr.Many}:   ecma402pr.Many,
		{start: ecma402pr.Zero, end: ecma402pr.One}:    ecma402pr.Zero,
		{start: ecma402pr.Zero, end: ecma402pr.Other}:  ecma402pr.Other,
		{start: ecma402pr.Zero, end: ecma402pr.Two}:    ecma402pr.Zero,
	},
	"en": {
		{start: ecma402pr.One, end: ecma402pr.Other}:   ecma402pr.Other,
		{start: ecma402pr.Other, end: ecma402pr.One}:   ecma402pr.Other,
		{start: ecma402pr.Other, end: ecma402pr.Other}: ecma402pr.Other,
	},
	"en-US": {
		{start: ecma402pr.One, end: ecma402pr.Other}:   ecma402pr.Other,
		{start: ecma402pr.Other, end: ecma402pr.One}:   ecma402pr.Other,
		{start: ecma402pr.Other, end: ecma402pr.Other}: ecma402pr.Other,
	},
	"fr": {
		{start: ecma402pr.One, end: ecma402pr.One}:     ecma402pr.One,
		{start: ecma402pr.One, end: ecma402pr.Other}:   ecma402pr.Other,
		{start: ecma402pr.Other, end: ecma402pr.Other}: ecma402pr.Other,
	},
	"hi": {
		{start: ecma402pr.One, end: ecma402pr.One}:     ecma402pr.One,
		{start: ecma402pr.One, end: ecma402pr.Other}:   ecma402pr.Other,
		{start: ecma402pr.Other, end: ecma402pr.Other}: ecma402pr.Other,
	},
	"pl": {
		{start: ecma402pr.Few, end: ecma402pr.Few}:     ecma402pr.Few,
		{start: ecma402pr.Few, end: ecma402pr.Many}:    ecma402pr.Many,
		{start: ecma402pr.Few, end: ecma402pr.Other}:   ecma402pr.Other,
		{start: ecma402pr.Many, end: ecma402pr.Few}:    ecma402pr.Few,
		{start: ecma402pr.Many, end: ecma402pr.Many}:   ecma402pr.Many,
		{start: ecma402pr.Many, end: ecma402pr.One}:    ecma402pr.One,
		{start: ecma402pr.Many, end: ecma402pr.Other}:  ecma402pr.Other,
		{start: ecma402pr.One, end: ecma402pr.Few}:     ecma402pr.Few,
		{start: ecma402pr.One, end: ecma402pr.Many}:    ecma402pr.Many,
		{start: ecma402pr.One, end: ecma402pr.Other}:   ecma402pr.Other,
		{start: ecma402pr.Other, end: ecma402pr.Few}:   ecma402pr.Few,
		{start: ecma402pr.Other, end: ecma402pr.Many}:  ecma402pr.Many,
		{start: ecma402pr.Other, end: ecma402pr.One}:   ecma402pr.One,
		{start: ecma402pr.Other, end: ecma402pr.Other}: ecma402pr.Other,
	},
	"zh": {
		{start: ecma402pr.Other, end: ecma402pr.Other}: ecma402pr.Other,
	},
	"zh-Hans": {
		{start: ecma402pr.Other, end: ecma402pr.Other}: ecma402pr.Other,
	},
	"zh-Hans-CN": {
		{start: ecma402pr.Other, end: ecma402pr.Other}: ecma402pr.Other,
	},
}
