// Code generated by tools/gen-plural-rules; DO NOT EDIT.
// CLDR version: 48.1.0

package plural

func SupportedLocales() []string {
	return []string{
		"ar",
		"en",
		"en-US",
		"fr",
		"hi",
		"pl",
		"zh",
		"zh-Hans",
		"zh-Hans-CN",
	}
}
