package codegen

import (
	"bytes"
	"fmt"
	"go/format"
)

const generatedHeader = `// Code generated by tools/gen-cldr; see SPECS/50-cldr-data.md#cldr-pin-rationale; DO NOT EDIT.

// Source: CLDR v48.1.0 / ICU 78 / tzdata 2025b (input hashes in internal/cldr/manifest.go)
// Generated: reproducible from tools/gen-cldr with pinned inputs; no timestamps or machine-local paths
// Schema: SPECS/50-cldr-data.md#cldr-data-package-convention
`

func FormatFile(src []byte) ([]byte, error) {
	formatted, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	if bytes.HasPrefix(formatted, []byte(generatedHeader)) {
		return formatted, nil
	}
	out := make([]byte, 0, len(generatedHeader)+len(formatted)+1)
	out = append(out, generatedHeader...)
	out = append(out, formatted...)
	return out, nil
}
