package codegen

import (
	"bytes"
	"fmt"
	"go/format"
)

const generatedHeader = "// Code generated by tools/gen-cldr; DO NOT EDIT.\n"

func FormatFile(src []byte) ([]byte, error) {
	formatted, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	if bytes.HasPrefix(formatted, []byte(generatedHeader)) {
		return formatted, nil
	}
	out := make([]byte, 0, len(generatedHeader)+len(formatted)+1)
	out = append(out, generatedHeader...)
	out = append(out, formatted...)
	return out, nil
}
