package codegen

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/agentable/go-intl/tools/gen-cldr/cldr"
	"github.com/agentable/go-intl/tools/gen-cldr/extract"
)

func TestRenderLeafCLDRFilesOwnsLocaleKernelFiles(t *testing.T) {
	t.Parallel()

	files, err := renderLeafCLDRFiles(minimalRuntimeInput())
	if err != nil {
		t.Fatalf("renderLeafCLDRFiles() error = %v", err)
	}

	byName := generatedFileSources(files)
	wantNames := localeKernelFileNames()
	assertStringSliceEqual(t, "renderLeafCLDRFiles() names", generatedFileNames(files), wantNames)

	for _, name := range wantNames {
		src := byName[name]
		assertSourceContains(t, name, src, "package cldrlocale")
		if strings.Contains(src, "package cldr\n") {
			t.Fatalf("%s still uses generator package name:\n%s", name, src)
		}
	}
	for name, wants := range map[string][]string{
		"locale/data.go":     {"const _data =", "const _localeBlob =", "const _maximizeBlob =", "const _numberingBlob ="},
		"locale/manifest.go": {"var dataManifest = DataManifest", `Generator: "tools/gen-cldr"`, `Name: "VERSION"`},
	} {
		assertSourceContainsAll(t, name, byName[name], wants...)
	}
}

func TestRenderRuntimeFilesKeepsRootCLDRRetired(t *testing.T) {
	t.Parallel()

	files, err := renderRuntimeFiles(minimalRuntimeInput())
	if err != nil {
		t.Fatalf("renderRuntimeFiles() error = %v", err)
	}

	byName := generatedFileSources(files)
	wantNames := runtimeFileNames()
	assertStringSliceEqual(t, "renderRuntimeFiles() names", generatedFileNames(files), wantNames)

	for _, forbidden := range retiredRootCLDRFileNames() {
		if _, ok := byName[forbidden]; ok {
			t.Fatalf("renderRuntimeFiles() emitted retired root CLDR file %q", forbidden)
		}
	}
	for _, name := range wantNames[len(localeKernelFileNames()):] {
		pkg, _, _ := strings.Cut(name, "/")
		assertSourceContains(t, name, byName[name], "package "+pkg)
	}
}

func TestRenderRuntimeWritesGeneratedFiles(t *testing.T) {
	t.Parallel()

	outDir := t.TempDir()
	if err := RenderRuntime(outDir, minimalRuntimeInput()); err != nil {
		t.Fatalf("RenderRuntime() error = %v", err)
	}

	for _, name := range runtimeFileNames() {
		path := filepath.Join(outDir, name)
		src, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("RenderRuntime() did not write %s: %v", name, err)
			continue
		}
		assertSourceContains(t, name, string(src), "// Code generated by tools/gen-cldr")
	}
	for _, forbidden := range retiredRootCLDRFileNames() {
		path := filepath.Join(outDir, forbidden)
		if _, err := os.Stat(path); !os.IsNotExist(err) {
			t.Errorf("RenderRuntime() retired root CLDR file %s stat error = %v, want not exist", forbidden, err)
		}
	}
}

func TestRenderRuntimeFilesWrapsDomainErrors(t *testing.T) {
	t.Parallel()

	input := minimalRuntimeInput()
	input.Units = unitTestData("fr", "meter")

	_, err := renderRuntimeFiles(input)
	assertErrorContainsAll(t, "renderRuntimeFiles()", err,
		"render internal/cldr/unit/data.go",
		`locale "fr" missing from kernel locale registry`,
	)
}

func TestRenderCLDRFileErrorNamesInternalOwner(t *testing.T) {
	t.Parallel()

	cause := errors.New("synthetic failure")
	err := renderCLDRFileError("locale/data.go", cause)
	if !errors.Is(err, cause) {
		t.Fatalf("renderCLDRFileError() does not preserve cause: %v", err)
	}
	assertErrorContainsAll(t, "renderCLDRFileError()", err,
		"render internal/cldr/locale/data.go",
		"synthetic failure",
	)
}

func minimalRuntimeInput() RuntimeInput {
	return RuntimeInput{
		Manifest: ManifestInput{
			Generator:     "tools/gen-cldr",
			CLDR:          "48.1.0",
			ICU:           "78",
			TZData:        "2025b",
			LocaleProfile: []string{"en"},
			InputHashes:   []ManifestHash{{Name: "VERSION", SHA256: "abc123"}},
		},
		Locales: extract.Locales{Tags: []string{"und", "en"}},
		LikelySubtags: extract.LikelySubtags{
			Maximize: map[string]extract.SubtagTriple{
				"en": {Lang: "en", Script: "Latn", Region: "US"},
			},
			Minimize: map[extract.SubtagTriple]string{
				{Lang: "en", Script: "Latn", Region: "US"}: "en",
			},
		},
		Numbers: extract.Numbers{
			"en": {DefaultNumberingSystem: "latn"},
		},
		Preferences: cldr.PreferenceData{
			HourCycle: map[string][]string{"US": {"h12", "h23"}},
			Week: map[string]cldr.WeekData{
				"US": {FirstDay: "sun", WeekendStart: "sat", WeekendEnd: "sun", MinDays: 1},
			},
			Calendar: map[string][]string{"US": {"gregory"}},
		},
	}
}

func generatedFileSources(files []generatedFile) map[string]string {
	byName := make(map[string]string, len(files))
	for _, file := range files {
		byName[file.name] = string(file.src)
	}
	return byName
}

func generatedFileNames(files []generatedFile) []string {
	names := make([]string, len(files))
	for i, file := range files {
		names[i] = file.name
	}
	return names
}

func retiredRootCLDRFileNames() []string {
	return []string{"data.go", "strings.go", "locales.go", "likely_subtags.go", "preference.go"}
}
