// Code generated by tools/gen-cldr; DO NOT EDIT.
package cldr

var collationValues = []string{
	"compat",
	"dict",
	"emoji",
	"eor",
	"phonebk",
	"phonetic",
	"pinyin",
	"searchjl",
	"stroke",
	"trad",
	"unihan",
	"zhuyin",
}
