// Code generated by tools/gen-cldr; DO NOT EDIT.
package cldr

type CurrencyData struct{ DefaultDigits, CashDigits, Rounding int }

type currencyNames struct {
	display        map[string]string
	symbol, narrow string
}

var currencyFractions = map[string]CurrencyData{
	"DEFAULT": {DefaultDigits: 2, CashDigits: 2, Rounding: 0},
	"JPY":     {DefaultDigits: 0, CashDigits: 0, Rounding: 0},
}

var currenciesByLocale = map[Locale]map[string]currencyNames{
	localeIndex["en"]: {
		"JPY": {display: map[string]string{"one": sliceRef{start: 23350, length: 12}.string(), "other": sliceRef{start: 23350, length: 12}.string()}, symbol: sliceRef{start: 23362, length: 2}.string(), narrow: sliceRef{start: 23362, length: 2}.string()},
		"USD": {display: map[string]string{"one": sliceRef{start: 23364, length: 9}.string(), "other": sliceRef{start: 23373, length: 10}.string()}, symbol: sliceRef{start: 23383, length: 1}.string(), narrow: sliceRef{start: 23383, length: 1}.string()},
	},
	localeIndex["hi"]: {
		"JPY": {display: map[string]string{"other": sliceRef{start: 23384, length: 28}.string()}, symbol: sliceRef{start: 23412, length: 4}.string(), narrow: sliceRef{start: 23362, length: 2}.string()},
		"USD": {display: map[string]string{"other": sliceRef{start: 23416, length: 25}.string()}, symbol: sliceRef{start: 23383, length: 1}.string(), narrow: sliceRef{start: 23383, length: 1}.string()},
	},
	localeIndex["zh"]: {
		"JPY": {display: map[string]string{"other": sliceRef{start: 23441, length: 6}.string()}, symbol: sliceRef{start: 23412, length: 4}.string(), narrow: sliceRef{start: 23362, length: 2}.string()},
		"USD": {display: map[string]string{"other": sliceRef{start: 23447, length: 6}.string()}, symbol: sliceRef{start: 23453, length: 3}.string(), narrow: sliceRef{start: 23383, length: 1}.string()},
	},
	localeIndex["zh-Hans"]: {
		"JPY": {display: map[string]string{"other": sliceRef{start: 23441, length: 6}.string()}, symbol: sliceRef{start: 23412, length: 4}.string(), narrow: sliceRef{start: 23362, length: 2}.string()},
		"USD": {display: map[string]string{"other": sliceRef{start: 23447, length: 6}.string()}, symbol: sliceRef{start: 23453, length: 3}.string(), narrow: sliceRef{start: 23383, length: 1}.string()},
	},
}

func CurrencyDigits(code string) CurrencyData {
	if data, ok := currencyFractions[code]; ok {
		return data
	}
	return currencyFractions["DEFAULT"]
}

func (l Locale) CurrencyDisplayName(code, plural string) string {
	if plural == "" {
		plural = "other"
	}
	data := currenciesByLocale[l][code]
	if name := data.display[plural]; name != "" {
		return name
	}
	return data.display["other"]
}

func (l Locale) CurrencySymbol(code, width string) string {
	data := currenciesByLocale[l][code]
	if width == "narrow" && data.narrow != "" {
		return data.narrow
	}
	return data.symbol
}
