// Code generated by tools/gen-plural-rules; DO NOT EDIT.
// CLDR version: 48.1.0

package cldr

import (
	"github.com/agentable/go-intl/internal/cldr/plural"
	ecma402pr "github.com/agentable/go-intl/internal/ecma402/pluralrules"
)

type Operand struct {
	N, I, F, T ecma402pr.OperandValue
	V, W, C, E int64
}

func NewOperand(formatted string) Operand {
	return operandFromRecord(ecma402pr.GetOperands(formatted, 0))
}

func NewCompactOperand(formatted string, exponent int) Operand {
	return operandFromRecord(ecma402pr.GetOperands(formatted, exponent))
}

type Form string

const (
	Zero  Form = "zero"
	One   Form = "one"
	Two   Form = "two"
	Few   Form = "few"
	Many  Form = "many"
	Other Form = "other"
)

func (l Locale) Cardinal(operand Operand) Form {
	rule, ok := plural.CardinalRule(l.pluralTag())
	if !ok {
		rule, _ = plural.CardinalRule("en")
	}
	return formOf(rule(operand.record()))
}

func (l Locale) Ordinal(operand Operand) Form {
	rule, ok := plural.OrdinalRule(l.pluralTag())
	if !ok {
		rule, _ = plural.OrdinalRule("en")
	}
	return formOf(rule(operand.record()))
}

func (l Locale) pluralTag() string {
	if int(l) < len(localeRecords) {
		return localeRecords[l].tag.string()
	}
	return "en"
}

func (o Operand) record() ecma402pr.OperandsRecord {
	return ecma402pr.OperandsRecord{
		N: o.N,
		I: o.I,
		F: o.F,
		V: int(o.V),
		W: int(o.W),
		T: o.T,
		C: int(o.C),
		E: int(o.E),
	}
}

func operandFromRecord(record ecma402pr.OperandsRecord) Operand {
	return Operand{
		N: record.N,
		I: record.I,
		F: record.F,
		V: int64(record.V),
		W: int64(record.W),
		T: record.T,
		C: int64(record.C),
		E: int64(record.E),
	}
}

func formOf(category ecma402pr.Category) Form {
	return Form(category.String())
}
