package cldr_test

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"golang.org/x/text/language"

	"github.com/agentable/go-intl/internal/cldr"
)

func TestCLDRGeneratedDataContract(t *testing.T) {
	t.Parallel()

	version := cldr.Version()
	if version.CLDR == "" || version.ICU == "" || version.TZData == "" {
		t.Fatalf("Version() = %#v, want all version fields populated", version)
	}

	loc, ok := cldr.ResolveLocale(language.MustParse("en"))
	if !ok {
		t.Fatal("ResolveLocale(en) failed")
	}
	if got := loc.CompactPattern("latn", "short", 3, "other"); got == "" {
		t.Fatal("CompactPattern(latn, 3, other) returned placeholder data")
	}
	if got := loc.DateFormat("gregorian", "short"); got == "" {
		t.Fatal("DateFormat(gregorian, short) returned placeholder data")
	}
	if got := loc.UnitPattern("meter", "long", "one"); got == "" {
		t.Fatal("UnitPattern(meter, long, one) returned placeholder data")
	}
}

func TestGeneratedFilesHaveHeaders(t *testing.T) {
	t.Parallel()

	root := filepath.Clean("../..")
	files, err := filepath.Glob(filepath.Join(root, "internal", "cldr", "*.go"))
	if err != nil {
		t.Fatalf("glob generated files: %v", err)
	}
	pluralFiles, err := filepath.Glob(filepath.Join(root, "internal", "cldr", "plural", "*.go"))
	if err != nil {
		t.Fatalf("glob generated plural files: %v", err)
	}
	files = append(files, pluralFiles...)
	for _, path := range files {
		name := filepath.Base(path)
		if strings.HasSuffix(name, "_test.go") || name == "cldr.go" || name == "doc.go" {
			continue
		}
		header := "// Code generated by tools/gen-cldr; DO NOT EDIT.\n"
		if name == "plurals.go" || strings.Contains(filepath.ToSlash(path), "/internal/cldr/plural/") {
			header = "// Code generated by tools/gen-plural-rules; DO NOT EDIT.\n"
		}
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			src, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("read file: %v", err)
			}
			if !bytes.HasPrefix(src, []byte(header)) {
				t.Fatalf("%s missing generated header", filepath.ToSlash(path))
			}
		})
	}
}

func TestGeneratedNoDrift(t *testing.T) {
	t.Parallel()

	root := filepath.Clean("../..")
	cldrDir := filepath.Join(root, "tools", "gen-cldr", ".cldr-json", "node_modules")
	if _, err := os.Stat(filepath.Join(cldrDir, "cldr-core")); err != nil {
		t.Skip("tools/gen-cldr/.cldr-json is absent; run task data:update to install the CLDR checkout")
	}

	out := filepath.Join(t.TempDir(), "cldr")
	if err := os.MkdirAll(out, 0o777); err != nil {
		t.Fatalf("mkdir output: %v", err)
	}
	profile := filepath.Join(root, "tools", "locale-profile.json")
	cmd := exec.Command("go", "-C", filepath.Join(root, "tools", "gen-cldr"), "run", ".", "-cldr-dir", ".cldr-json/node_modules", "-out", out, "-version-file", filepath.Join(root, "internal", "cldr", "VERSION"), "-profile", profile)
	cmd.Env = os.Environ()
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("run gen-cldr: %v\n%s", err, output)
	}
	pluralCmd := exec.Command(
		"go",
		"-C", filepath.Join(root, "tools", "gen-plural-rules"),
		"run", ".",
		"-plurals", filepath.Join(root, "tools", "gen-cldr", ".cldr-json", "node_modules", "cldr-core", "supplemental", "plurals.json"),
		"-ranges", filepath.Join(root, "tools", "gen-cldr", ".cldr-json", "node_modules", "cldr-core", "supplemental", "pluralRanges.json"),
		"-out", filepath.Join(out, "plural"),
		"-profile", profile,
	)
	pluralCmd.Env = os.Environ()
	output, err = pluralCmd.CombinedOutput()
	if err != nil {
		t.Fatalf("run gen-plural-rules: %v\n%s", err, output)
	}

	files, err := filepath.Glob(filepath.Join(root, "internal", "cldr", "*.go"))
	if err != nil {
		t.Fatalf("glob generated files: %v", err)
	}
	pluralFiles, err := filepath.Glob(filepath.Join(root, "internal", "cldr", "plural", "*.go"))
	if err != nil {
		t.Fatalf("glob generated plural files: %v", err)
	}
	files = append(files, pluralFiles...)
	for _, path := range files {
		name := filepath.Base(path)
		if strings.HasSuffix(name, "_test.go") || name == "cldr.go" || name == "doc.go" {
			continue
		}
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			want, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("read committed file: %v", err)
			}
			rel, err := filepath.Rel(filepath.Join(root, "internal", "cldr"), path)
			if err != nil {
				t.Fatalf("relative path: %v", err)
			}
			got, err := os.ReadFile(filepath.Join(out, rel))
			if err != nil {
				t.Fatalf("read generated file: %v", err)
			}
			if !bytes.Equal(got, want) {
				t.Fatalf("%s drifted from generator output", name)
			}
		})
	}
}
