// Code generated by tools/gen-cldr; DO NOT EDIT.
package cldr

type unitData struct {
	patterns map[string]map[string]map[string]string
	compound map[string]string
}

var unitsByLocale = map[Locale]map[string]unitData{
	localeIndex["en"]: {
		"meter": {patterns: map[string]map[string]map[string]string{"long": map[string]map[string]string{"meter": map[string]string{"one": sliceRef{start: 48528, length: 9}.string(), "other": sliceRef{start: 48537, length: 10}.string()}}, "narrow": map[string]map[string]string{"meter": map[string]string{"one": sliceRef{start: 48547, length: 4}.string(), "other": sliceRef{start: 48547, length: 4}.string()}}, "short": map[string]map[string]string{"meter": map[string]string{"one": sliceRef{start: 48551, length: 5}.string(), "other": sliceRef{start: 48551, length: 5}.string()}}}, compound: map[string]string{"long": sliceRef{start: 48556, length: 11}.string(), "narrow": sliceRef{start: 48567, length: 7}.string(), "short": sliceRef{start: 48567, length: 7}.string()}},
	},
	localeIndex["zh"]: {
		"meter": {patterns: map[string]map[string]map[string]string{"long": map[string]map[string]string{"meter": map[string]string{"other": sliceRef{start: 48574, length: 6}.string()}}, "narrow": map[string]map[string]string{"meter": map[string]string{"other": sliceRef{start: 48574, length: 6}.string()}}, "short": map[string]map[string]string{"meter": map[string]string{"other": sliceRef{start: 48574, length: 6}.string()}}}, compound: map[string]string{"long": sliceRef{start: 48580, length: 9}.string(), "narrow": sliceRef{start: 48567, length: 7}.string(), "short": sliceRef{start: 48567, length: 7}.string()}},
	},
	localeIndex["zh-Hans"]: {
		"meter": {patterns: map[string]map[string]map[string]string{"long": map[string]map[string]string{"meter": map[string]string{"other": sliceRef{start: 48574, length: 6}.string()}}, "narrow": map[string]map[string]string{"meter": map[string]string{"other": sliceRef{start: 48574, length: 6}.string()}}, "short": map[string]map[string]string{"meter": map[string]string{"other": sliceRef{start: 48574, length: 6}.string()}}}, compound: map[string]string{"long": sliceRef{start: 48580, length: 9}.string(), "narrow": sliceRef{start: 48567, length: 7}.string(), "short": sliceRef{start: 48567, length: 7}.string()}},
	},
}

func (l Locale) UnitPattern(unit, width, plural string) string {
	if width == "" {
		width = "long"
	}
	if plural == "" {
		plural = "other"
	}
	return unitsByLocale[l][unit].patterns[width][unit][plural]
}

func (l Locale) CompoundUnitPattern(width string) string {
	if width == "" {
		width = "long"
	}
	for _, data := range unitsByLocale[l] {
		if pattern := data.compound[width]; pattern != "" {
			return pattern
		}
	}
	return ""
}
